#pragma once
#include "types/GI_MessageLoop.hpp"
#include "types/Windows_group.hpp"

namespace Types {
    struct TPoint;

} // namespace Types

namespace GI_MessageLoop {
    extern pas::List* MessageLoopStack;

    // Consumes the mouse move generated by viewport cursor recentering.
    extern std::uint8_t IgnoreWarpMouseMove;

    // Written by ProcessWindowMessage and reused by RefreshMouseDispatch.
    extern WindowsSdk::TPoint LastMousePosition;

    void PushMessageLoop(TMessageLoopGI* Loop);

    void PopMessageLoop(TMessageLoopGI* Loop);

    // Callback pairs contain a Delphi method's code and instance pointers.
    // Mouse move and button callbacks receive Context/EAX, Sender/EDX, key state/ECX and Point on stack;
    // key callbacks receive Context/EAX, Sender/EDX and virtual key/ECX.
    // Code blocks are borrowed from the UI configuration.
    // PositionModeW is the fourth Pos component ('w'); selects the parent's coordinate mode.
    // Notify callbacks receive Context in EAX and this object in EDX.
    void TObjectGI_Create(TObjectGI* Self, TObjectGI* Owner);

    void TObjectGI_Destroy(TObjectGI* Self);

    // Each string is a sound name; its Data slot stores an integer weight.
    void TFormSoundGroup_Create(TFormSoundGroup* Self);

    void TFormSoundGroup_Destroy(TFormSoundGroup* Self);

    void TMessageLoopGI_Create(TMessageLoopGI* Self);

    void TMessageLoopGI_Destroy(TMessageLoopGI* Self);

    // Contains a native handwritten PUSHAD/POPAD loop.
    void TMessageLoopGI_RestoreSavedPixels16(TMessageLoopGI* Self);

    // Dispatches mouse/keyboard messages, deferred UI code and layout-inspector keys. Button coordinates are unsigned words; move and wheel coordinates are signed.
    inline void TMessageLoopGI_ProcessWindowMessage(GI_MessageLoop::TMessageLoopGI* Self, std::uint32_t Message, std::uint32_t WParam, std::int32_t LParam);

} // namespace GI_MessageLoop

#include "inline/GI_MessageLoop.hpp"
