#pragma once
#include "types/ab_MainForm.hpp"

namespace ab_MainForm {
    static_assert(sizeof(void*) != 4 || sizeof(ab_MainForm::TArcadeMapDrag) == 9);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapDrag, Active) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapDrag, Position) == 1);
    static_assert(sizeof(void*) != 4 || sizeof(ab_MainForm::TfAB) == 856);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, MapPanel) == 208);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WorldPanel) == 212);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, StarField) == 216);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, StartStarImage) == 220);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, EndStarImage) == 224);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ItemPanel) == 228);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ItemInfoWindow) == 232);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, AutoButton) == 236);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ManualButton) == 240);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, BattleHelpLabel) == 244);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, VictoryPanel) == 248);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, DefeatPanel) == 252);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, PlayerVisual) == 256);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, PlayerMapPosition) == 260);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ShipPath) == 268);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, RouteSpaces) == 272);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, MapDrag) == 276);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ScrollTimer) == 288);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, MapBackgroundPath) == 292);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WeaponButtons) == 296);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WeaponIcons) == 316);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WeaponChargeImages) == 336);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WeaponPrimaryImages) == 356);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WeaponSecondaryImages) == 376);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, PlayButton) == 400);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, PauseButton) == 404);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WorldLines) == 408);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, UpdateTimer) == 412);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WorldCenterX) == 416);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, WorldCenterY) == 420);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, BonusIcons) == 424);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, BonusRings) == 456);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, EnemyIcons) == 488);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, EnemyHealthRings) == 520);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, EnemyRewardIcons) == 552);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, EnemyRewardBackdrops) == 584);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, TrackedShipIcons) == 616);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, TrackedShipHealthRings) == 648);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CampaignWeapons) == 680);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ForwardKeyDown) == 700);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ReverseKeyDown) == 701);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, BrakeKeyDown) == 702);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, TurnLeftKeyDown) == 703);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, TurnRightKeyDown) == 704);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, PrimaryFireKeyDown) == 705);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, SecondaryFireKeyDown) == 706);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, GridLines) == 708);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, MapState2C8) == 712);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, Text2CC) == 716);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, OverlaySegments) == 736);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, TransitionSpeed) == 784);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CampaignTransitionStarted) == 792);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CampaignLoadStarted) == 793);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CampaignLoadFinished) == 794);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CacheLoader) == 796);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, DefeatCountdownTicks) == 800);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CampaignLoadProgress) == 804);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, DepartureTurn) == 808);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ArrivalTurn) == 812);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, InfoObject) == 816);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CargoPickupItem) == 820);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, CargoPickupZone) == 824);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, InitialRandomSeed) == 828);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, RandomSeed) == 832);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ViewModeBeforeDefeat) == 836);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, SimulationPaused) == 837);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, VictoryTimer) == 840);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, ListedObjects) == 844);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, LoadPanel) == 848);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TfAB, SelectedMapName) == 852);
    static_assert(sizeof(void*) != 4 || sizeof(ab_MainForm::TArcadeMapColorHeader) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorHeader, CurrentColor) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorHeader, VariantCount) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorHeader, SelectedVariant) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorHeader, ByteSize) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(ab_MainForm::TArcadeMapColorVariant) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorVariant, SequenceOffset) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorVariant, AppearanceTag) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(ab_MainForm::TArcadeMapColorSequence) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorSequence, FrameIndex) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(ab_MainForm::TArcadeMapColorSequence, FrameCount) == 4);

} // namespace ab_MainForm
