#pragma once
#include "types/aConst.hpp"

namespace aConst {
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TWeaponInfo) == 120);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, ItemType) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, ConfigName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, TechLevel) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, InventionIndex) == 9);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, CostFactor) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, MinDamage) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, MaxDamage) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, AverageSize) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, AverageRange) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, ShotSpeedPercent) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, MissileRange) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, MissileMaxSpeed) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, MissileMinSpeed) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, MissileChanceToBeHit) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, DamageFlags) == 49);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, ShotType) == 53);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, ShotCount) == 54);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, AttackCount) == 55);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, SecondaryDamageRadius) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, MiningFactor) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, DamageScaleByLevel) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, PrimarySE) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, SecondarySE) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, AreaSE) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, DefaultPalette) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, Availability) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, ArcadeWeaponType) == 113);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TWeaponInfo, TypeHash) == 116);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TRewardInfo) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TRewardInfo, AwardId) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TRewardInfo, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TRewardInfo, Text) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TMicroModuleInfo) == 292);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, SpecialOnly) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, BlocksMicroModuleSlot) == 1);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, BlocksSpecialSlot) == 2);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, NamePrefix) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, Color) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, TextReplace) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, StatBonuses) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, CostPercent) == 192);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, SizePercent) == 196);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, FragilityFactor) == 200);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, FragilityFactorByDamageClass) == 204);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, Priority) == 216);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, AllowedHullOwnerMask) == 217);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, AllowedCustomHullFactions) == 220);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, CustomFaction) == 224);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, AllowedDominatorSeriesMask) == 228);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, AllowedItemTypes) == 229);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, AllowedCustomWeaponTypes) == 240);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, OfferStationTypes) == 244);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, OfferStationNames) == 248);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, OnPlanets) == 252);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, RacialRestriction) == 253);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, SeparatedNumbers) == 254);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, ConfigNumber) == 256);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, ConfigName) == 260);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, ConfigNameHash) == 264);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, KindGraph) == 268);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, MissileGraph) == 272);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, ShotVisual) == 276);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, HullGraphSizePercent) == 280);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, CustomTag) == 284);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TMicroModuleInfo, WeaponDamageFlags) == 288);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TPrimaryDamageTypeInfo) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TPrimaryDamageTypeInfo, Kind) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TPrimaryDamageTypeInfo, BonusKind) == 1);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TPrimaryDamageTypeInfo, Name) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::THullLevelStats) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullLevelStats, Armor) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullLevelStats, Fragility) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::THullTypeInfo) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, Name) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, Text) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, AllowedOwners) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, AllowedShipTypes) == 9);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, SlotBonuses) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, SizePercent) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, CostPercent) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, FragilityFactor) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, FragilityByDamageClass) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, Year) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, ProbabilityWeight) == 84);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, SortKey) == 88);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, SystemName) == 92);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::THullTypeInfo, SystemNameCRC) == 96);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TOwnerInfo) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, InternalName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, DisplayName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, FuelPriceFactor) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, EquipmentDurabilityFactor) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, MinimumAfterburnerWear) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, MaximumAfterburnerWear) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, FearThresholdScale) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TOwnerInfo, ColorTag) == 28);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TGoodsInfo) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, InternalName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, DisplayName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, TradeName) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, BaseStock) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, MinPrice) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, AveragePrice) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, MaxPrice) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, TradeExperienceFactor) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, EconomyFactors) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGoodsInfo, PirateEconomyFactor) == 44);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TGovermentInfo) == 160);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGovermentInfo, InternalName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGovermentInfo, DisplayName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGovermentInfo, RevolutionRelationDelta) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGovermentInfo, QuestOfferProbabilities) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TGovermentInfo, GoodsFactors) == 32);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TRelationTypeInfo) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TRelationTypeInfo, InternalName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TRelationTypeInfo, DisplayName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TRelationTypeInfo, MinimumValue) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TKlingTypeInfo) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, DisplayNames) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, MinimumHullSize) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, MaximumHullSize) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, InitialWealthScale) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, BaseNodeReserve) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, KillExperience) == 34);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, RankPoints) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, PirateRankPoints) == 38);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, RankImageIndex) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TKlingTypeInfo, FactionStrengthWeight) == 48);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TEconomyInfo) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TEconomyInfo, InternalName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TEconomyInfo, DisplayName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TEconomyInfo, ShortDisplayName) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TEconomyInfo, InventionProgressScale) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TIllnessInfo) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, Name) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, Text) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, AllowedLocationOwners) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, AllowedOwners) == 9);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, AllowedRatingBands) == 10);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, AllowedRanks) == 11);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, AllowedCareers) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, MedicalPriceSizeLevel) == 13);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, DevelopmentRate) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, InfectionChance) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, Locations) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, Disabled) == 33);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TIllnessInfo, Duration) == 36);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TShipTypeInfo) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TShipTypeInfo, Name) == 0);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::SEquipment) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::SEquipment, ItemType) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::SEquipment, Name) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TStationEquipmentOfferQuota) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, Hulls) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, FuelTanks) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, Engines) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, Radars) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, Scanners) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, RepairRobots) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, CargoHooks) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, DefGenerators) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStationEquipmentOfferQuota, Weapons) == 32);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::TStatusInfo) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStatusInfo, Name) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStatusInfo, MinimumWealthToAverageRatio) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStatusInfo, MinimumWealthToBestRatio) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStatusInfo, MinimumStrengthToAverageRatio) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::TStatusInfo, MinimumStrengthToBestRatio) == 32);
    static_assert(sizeof(void*) != 4 || sizeof(aConst::tInventionInfo) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::tInventionInfo, Name) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::tInventionInfo, InitialLevel) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aConst::tInventionInfo, RequiredMainTechLevel) == 5);

} // namespace aConst
