#pragma once
#include "types/aEFilm.hpp"

namespace aEFilm {
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmCameraEvent) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCameraEvent, StepIndex) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCameraEvent, Priority) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCameraEvent, StartPosition) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCameraEvent, EndPosition) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilm) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, FirstObject) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, LastObject) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, FirstCommand) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, LastCommand) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, FirstFreeCommand) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, LastFreeCommand) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, CameraEvents) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, CameraEventCount) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, StringTable) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, DataBuffers) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, SystemProcessName) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, MapDiameter) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, RadarRange) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, Turn) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, PlayerCombatRecorded) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, BackgroundImage) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, StarGenerationSeed) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, InitialActivity) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, FinalActivity) == 76);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, CameraAnchor) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, ForceCameraMovement) == 88);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilm, ObjectInfo) == 92);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmObj) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObj, Prev) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObj, Next) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObj, ObjectId) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObj, SceneObject) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObj, KindName) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObj, GraphKey) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmCommand) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCommand, Prev) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCommand, Next) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCommand, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCommand, StepIndex) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmCommand, Payload) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmObjectCommand) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObjectCommand, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObjectCommand, StepIndex) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObjectCommand, Obj) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObjectCommand, Value) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObjectCommand, ExtraValue) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmObjectCommand, Flags) == 28);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmByteCommand) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmByteCommand, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmByteCommand, StepIndex) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmByteCommand, Obj) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmByteCommand, Value) == 20);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmVectorCommand) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmVectorCommand, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmVectorCommand, StepIndex) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmVectorCommand, Obj) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmVectorCommand, Position) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmVectorCommand, ForceMovement) == 28);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmHitCommand) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmHitCommand, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmHitCommand, StepIndex) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmHitCommand, Obj) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmHitCommand, Color) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmHitCommand, Damage) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmHitCommand, Destroyed) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmHitCommand, PlaySound) == 29);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmEndpointsCommand) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmEndpointsCommand, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmEndpointsCommand, StepIndex) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmEndpointsCommand, Obj) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmEndpointsCommand, Source) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmEndpointsCommand, Target) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(aEFilm::TEFilmSizeCommand) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmSizeCommand, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmSizeCommand, StepIndex) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmSizeCommand, Obj) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmSizeCommand, Size) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aEFilm::TEFilmSizeCommand, TailMode) == 28);

} // namespace aEFilm
