#pragma once
#include "types/aGalaxy.hpp"

namespace aGalaxy {
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TDominatorResearchEntry) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TDominatorResearchEntry, Progress) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TDominatorResearchEntry, Material) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TSpaceBackgroundEntry) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TSpaceBackgroundEntry, ImageIndex) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TSpaceBackgroundEntry, OrbitCenter) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TSpaceBackgroundEntry, Position) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TSpaceBackgroundEntry, Unknown38) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TSpaceBackgroundEntry, OrbitStepDegrees) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TSpaceBackgroundEntry, FrameIndex) == 88);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TGalaxy) == 476);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextConstellationId) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextStarId) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextHoleId) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextPlanetId) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextSputnikId) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextAsteroidId) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextShipId) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextItemId) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextMissileId) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, PlayerRangerIndex) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, Stars) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, Holes) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, StoredItems) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, Planets) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, Rangers) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, PirateCount) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, PirateClanCount) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TransportCount) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, CurrentTurn) == 76);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, DifficultyLevels) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, GenerationSeed) == 88);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, RandomState) == 92);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, AverageRangerCapital) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, MaxRangerWealth) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, AverageRangerStrength) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, BestRangerStrength) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, StrongestRanger) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, WealthiestRanger) == 116);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, EminentCareerShips) == 120);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, ShipTypeCounts) == 132);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextPlanetNewsId) == 188);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, PlanetNews) == 192);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, CustomWeaponTypes) == 196);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, KellerTargetStar) == 200);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, KellerMissionState) == 204);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, ChecksumScalarD0) == 208);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, DominatorResearch) == 212);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, ChecksumScalarEC) == 236);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TechLevel) == 240);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, WarDeltaWin) == 244);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, RangerSpawnQuotas) == 256);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TerronWeaponLockTurn) == 276);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TerronGrowLockTurn) == 280);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TerronLandingLockTurn) == 284);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TerronToStarTurn) == 288);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, KellerLeaveTurn) == 292);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, KellerResearchTargetStarId) == 296);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, BlazerLandingPlanetId) == 300);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, BlazerSelfDestructTurn) == 304);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TerronSeriesResolvedTurn) == 308);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, KellerSeriesResolvedTurn) == 312);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, BlazerSeriesResolvedTurn) == 316);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, PirateWinTurn) == 320);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, PirateWinType) == 324);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, CoalitionDefeatedTurn) == 328);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, GraphDominatorSurfacesEnabled) == 332);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, SpaceEffectKind) == 333);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, Scripts) == 336);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, LiberationGroups) == 340);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, JumpGates) == 344);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, ShipsInTransit) == 348);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, ConstellationCount) == 352);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, Constellations) == 356);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, ConstellationOutlineJunctions) == 360);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, SpaceBackgroundEntries) == 364);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, SaveCount) == 368);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, LoadCount) == 372);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, PendingEquipmentPurchasePrice) == 376);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, IronWill) == 380);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, DominatorModLevel) == 381);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, TechnicModEnabled) == 382);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, AmmoModEnabled) == 383);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, GodModEnabled) == 384);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, UltraScanModEnabled) == 385);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, StasisModEnabled) == 386);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, CampaignFlag183) == 387);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, FinalizationNameEncoded) == 388);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, CustomRules) == 392);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, NextSpecialStationServiceTurn) == 432);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, GalaxyEvents) == 436);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, InterfaceStateOverrides) == 440);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, InterfaceTextOverrides) == 444);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, InterfaceImageOverrides) == 448);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, InterfacePositionOverrides) == 452);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, InterfaceSizeOverrides) == 456);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, LoadedShips) == 460);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, ScoreScreenDismissed) == 464);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, Destroying) == 465);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, GenerationMachineHash) == 468);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, SpecialSimulationMode) == 472);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TGalaxy, CheatsDisabled) == 473);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TStarDistanceEntry) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStarDistanceEntry, Distance) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStarDistanceEntry, Star) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TStar) == 276);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Id) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, GenerationSeed) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, RandomState) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Name) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Position) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, SystemRadius) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, MapDiameter) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Planets) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Asteroids) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Ships) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Items) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, MovingDropItems) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Missiles) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, SystemProcessName) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Status) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, SafeRadius) == 92);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, DamageRadius) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Reserved64) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Radius) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Graphic) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, DaysSincePlayerVisit) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, DaysSinceLastNpcShipSpawn) == 116);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, PlayerPresenceLevel) == 120);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, BackgroundImage) == 124);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Flag80) == 128);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, LastDominatorPresenceTurn) == 132);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, LastPiratePresenceTurn) == 136);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, LastLiberationRewardsTurn) == 140);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, LiberationRewardsPending) == 144);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, StarDistances) == 148);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, ShipTypeCounts) == 152);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Constellation) == 208);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, ConstellationGraphIndex) == 212);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, NoComeKling) == 216);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, Dominion) == 220);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, MapLabel) == 224);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, CustomSystemInfos) == 228);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, CurrentStepIndex) == 232);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, SimulationStepCount) == 236);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, RecordingTurnFilm) == 240);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, PlayerCombatOccurred) == 241);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, InterruptLongTravel) == 242);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, KeepFilmRunning) == 243);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, CombatEvents) == 244);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, PendingFilmObjectRemovals) == 248);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, ReferencedItems) == 252);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, PlayerFilmPath) == 256);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, MovementStepCount) == 260);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStar, MovementStepScale) == 264);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TConstellation) == 140);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, Id) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, HomeDistanceTier) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, Visible) == 9);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, MapCenter) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, OutlineGrowthStepsRemaining) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, Stars) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, AdjacentConstellations) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, OutlineSegments) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, HiddenOutlineSegmentsBackup) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, BoundaryRaySamples) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, OutlineBounds) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, OutlineBoundsSize) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, StarLinks) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, ShipTypeCounts) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, OutlinePolygons) == 128);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, HiddenOutlinePolygonsBackup) == 132);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellation, SerializedValue88) == 136);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TStoredItem) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStoredItem, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStoredItem, Item) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TJumpGateEntry) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TJumpGateEntry, Gate) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TJumpGateEntry, UsedThisTurn) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TJumpGateEntry, GateFilmId) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TJumpGateEntry, Effect) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TJumpGateEntry, EffectFilmId) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::THole) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, Id) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, Star1) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, Position1) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, Star2) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, Position2) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, CreatedTurn) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, HoleType) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, Graphic) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, FilmObjectId) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::THole, ArcadeMapName) == 48);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TMovingDropItemEntry) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TMovingDropItemEntry, Payload) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TMovingDropItemEntry, Destination) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TMovingDropItemEntry, SourceShipId) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TMovingDropItemEntry, InsertedIntoStar) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TMovingDropItemEntry, DeployTranclucator) == 17);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TInterfaceStateOverride) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceStateOverride, FormName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceStateOverride, ControlPath) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceStateOverride, State) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceStateOverride, OriginalState) == 13);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TInterfaceTextOverride) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceTextOverride, FormName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceTextOverride, ControlPath) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceTextOverride, Text) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceTextOverride, OriginalText) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TInterfaceImageOverride) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceImageOverride, FormName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceImageOverride, ControlPath) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceImageOverride, ImagePath) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceImageOverride, OriginalImagePath) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TInterfacePosOverride) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfacePosOverride, FormName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfacePosOverride, ControlPath) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfacePosOverride, Position) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfacePosOverride, Depth) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfacePosOverride, OriginalPosition) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfacePosOverride, OriginalDepth) == 40);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TInterfaceSizeOverride) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceSizeOverride, FormName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceSizeOverride, ControlPath) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceSizeOverride, Size) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TInterfaceSizeOverride, OriginalSize) == 20);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TStarCombatEvent) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStarCombatEvent, StepIndex) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStarCombatEvent, CombatGroup) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStarCombatEvent, Attacker) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStarCombatEvent, Target) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TStarCombatEvent, Weapon) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TCustomSystemInfo) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TCustomSystemInfo, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TCustomSystemInfo, Icon) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TCustomSystemInfo, Info) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TCustomSystemInfo, TypeTag) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TCustomSystemInfo, Distance) == 20);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TConstellationStarLink) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationStarLink, StartPoint) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationStarLink, EndPoint) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationStarLink, StartStarIndex) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationStarLink, EndStarIndex) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationStarLink, TraversalMark) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TMapLineSegment) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TMapLineSegment, StartPoint) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TMapLineSegment, EndPoint) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxy::TConstellationBoundaryRaySample) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationBoundaryRaySample, Position) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationBoundaryRaySample, Direction) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationBoundaryRaySample, Angle) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxy::TConstellationBoundaryRaySample, GrowthStopped) == 20);

} // namespace aGalaxy
