#pragma once
#include "types/aGalaxyStruct.hpp"

namespace aGalaxyStruct {
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TGalaxyCustomRules) == 39);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, Enabled) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, DominatorStrength) == 1);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, DominatorAggression) == 2);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, DominatorSpawn) == 3);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, PirateAggression) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, CoalitionAggression) == 5);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, AsteroidModifier) == 6);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, SunDamageModifier) == 7);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ExtraInventions) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, AcrynModifier) == 9);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, NodeDropModifier) == 10);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ArcadeDropValueModifier) == 11);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, DropValueModifier) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, AgriculturalPlanetWeight) == 13);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, MixedPlanetWeight) == 14);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, IndustrialPlanetWeight) == 15);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ExtraRangers) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ArcadeHitpointsModifier) == 17);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ArcadeDamageModifier) == 18);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, AIJunkTolerance) == 19);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ChaoticRandom) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, UnrestrictedEquipmentKnowledge) == 21);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, StationsNearStars) == 22);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, FullStationTargeting) == 23);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, SpecialShips) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ZeroStartingExperience) == 25);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ArcadeBattleRoyale) == 26);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, DominatorRacialWeapons) == 27);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, StartInCenter) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, MaxRangeMissiles) == 29);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, OldHyperspace) == 30);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, PirateNodes) == 31);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, AIUseShops) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, StationsUseShop) == 33);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, DuplicateArtefacts) == 34);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, HullGrowth) == 35);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, ArcadeEquipmentChange) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, OldSpeedCalculation) == 37);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyCustomRules, OldMissileBonuses) == 38);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TStarStatus) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, ThreatLevel) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, TrafficLevel) == 1);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, ControlFaction) == 2);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, CustomFaction) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, Battle) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, DominatorSeries) == 9);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, PreviousControlFaction) == 10);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, CachedFactionStrength) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TStarStatus, FactionStrengthCacheTurn) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TGoodsTradePriceEntry) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGoodsTradePriceEntry, Count) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGoodsTradePriceEntry, PriceState) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGoodsTradePriceEntry, PurchasePrice) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGoodsTradePriceEntry, BaseSalePrice) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TPlanetNews) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetNews, Id) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetNews, Turn) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetNews, NewsType) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetNews, Text) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TEngineLevelStats) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TEngineLevelStats, Speed) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TEngineLevelStats, JumpRange) == 2);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TCargoHookLevelStats) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TCargoHookLevelStats, PickupPower) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TCargoHookLevelStats, Range) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TCargoHookLevelStats, MinPullSpeed) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TCargoHookLevelStats, MaxPullSpeed) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TGalaxyDifficultyTuning) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, GoodsEventDurationFactor) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, QuestTimeAndExperienceFactor) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, EquipmentWearFactor) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, InventionProgressScale) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, ArcadeRewardScale) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, QuestMoneyFactor) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, DifficultyValue18) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, DifficultyValue1C) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, MarketPriceBandSqueeze) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, RandomHoleSpawnRollMaximum) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, MaximumDominatorResearchRate) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, MaximumResearchMaterialConsumption) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, MaximumQuestProgramRewardCount) == 45);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, ArcadeDamageTakenScale) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TGalaxyDifficultyTuning, DifficultyFactor34) == 52);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TPlanetGoodsFactors) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetGoodsFactors, PriceFactor) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetGoodsFactors, StockFactor) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TQuestTuning) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TQuestTuning, RewardCapitalPercent) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TQuestTuning, BaseDuration) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TQuestTuning, BaseRewardMoney) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TPlanetOwnerMasks) == 3);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetOwnerMasks, Coalition) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetOwnerMasks, Dominators) == 1);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetOwnerMasks, PirateClan) == 2);
    static_assert(sizeof(void*) != 4 || sizeof(aGalaxyStruct::TPlanetRaceMarketInfo) == 168);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, InventionProgressScale) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, InitialInventionBoostCount) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, GoodsFactors) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, GovernmentRollThresholds) == 136);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, RevolutionChance) == 144);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, FriendlyRelationScale) == 148);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, PirateRelationFactor) == 152);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, UnknownFactor9C) == 156);
    static_assert(sizeof(void*) != 4 || offsetof(aGalaxyStruct::TPlanetRaceMarketInfo, PirateRelationCeiling) == 160);

} // namespace aGalaxyStruct
