#pragma once
#include "types/aItem.hpp"

namespace aItem {
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TItem) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, GraphObject) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, Id) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, ItemType) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, Position) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, Weight) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, OwnerId) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, Cost) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, NameOverride) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, FilmObject) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, ScriptItem) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, DestroyFlag) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TItem, NoDropFlag) == 52);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TEquipment) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, ConfigBlockName) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, CustomFaction) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, ConditionPercent) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, BrokenFlag) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, EquippedFlag) == 73);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, AssignedSlotData) == 76);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, MicroModuleIndex) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, SpecialModuleIndex) == 84);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, ExtraSpecials) == 88);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, DominatorSeries) == 92);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipment, DetailImprovement) == 93);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::THull) == 132);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, HullPoints) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, TechLevel) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, Armor) == 101);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, HullType) == 102);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, HullSeries) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, OwnerShip) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, CapitalShip) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, PirateBuilt) == 113);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, ImpulseShieldsEnabled) == 114);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, InterceptorsEnabled) == 115);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, Energy) == 116);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, EnergyMax) == 120);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, InterceptorTarget) == 124);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, InterceptorTargetingStrategy) == 128);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::THull, InterceptorPassCountOverride) == 129);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TFuelTanks) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TFuelTanks, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TFuelTanks, Fuel) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TFuelTanks, Capacity) == 104);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TEngine) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEngine, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEngine, Speed) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEngine, JumpRange) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEngine, OutputPercent) == 105);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TRadar) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TRadar, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TRadar, Range) == 100);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TScaner) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TScaner, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TScaner, ScanPower) == 97);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TRepairRobot) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TRepairRobot, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TRepairRobot, RepairPoints) == 97);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TCargoHook) == 116);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCargoHook, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCargoHook, PickupPower) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCargoHook, Range) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCargoHook, MinPullSpeed) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCargoHook, MaxPullSpeed) == 112);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TDefGenerator) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TDefGenerator, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TDefGenerator, DamageFactor) == 100);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TWeapon) == 128);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, TechLevel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, Range) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, MinDamage) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, MaxDamage) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, Target) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, LoadedTargetKind) == 116);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, Ammo) == 120);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TWeapon, AmmoCapacity) == 124);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TSatellite) == 116);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TSatellite, SatelliteTypeId) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TSatellite, TargetPlanet) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TSatellite, TrajectoryIndex) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TSatellite, WearPerTurn) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TSatellite, WaterExplorationRate) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TSatellite, LandExplorationRate) == 113);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TSatellite, HillExplorationRate) == 114);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TEquipmentWithActCode) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipmentWithActCode, ActionCode) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipmentWithActCode, ActCodeInitialized) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TEquipmentWithActCode, DisplayAsArtefact) == 101);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TArtefact) == 104);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TArtefactCustom) == 132);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactCustom, CountsAsItemType) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactCustom, SharedUse) == 105);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactCustom, SharedEffect) == 106);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactCustom, Data) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactCustom, TextData1) == 120);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactCustom, TextData2) == 124);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactCustom, TextData3) == 128);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TExtraSpecial) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TExtraSpecial, ModuleIndexPlusOne) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TExtraSpecial, Count) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TUselessItem) == 120);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TUselessItem, CustomText) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TUselessItem, Data) == 108);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TMicroModule) == 96);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TCistern) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCistern, Fuel) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCistern, Capacity) == 100);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TGoods) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TGoods, Quantity) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TGoods, NaturalFlag) == 60);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TCountableItem) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCountableItem, StackCount) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCountableItem, DropFlag) == 100);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TProtoplasm) == 104);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TArtefactTranclucator) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactTranclucator, Ship) == 104);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TArtefactTransmitter) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TArtefactTransmitter, Power) == 104);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TTreasureMap) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TTreasureMap, TargetPlanet) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TTreasureMap, SourceShipName) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TTreasureMap, PreviewTablePage1) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TTreasureMap, PreviewTablePage2) == 108);
    static_assert(sizeof(void*) != 4 || sizeof(aItem::TCustomWeapon) == 132);
    static_assert(sizeof(void*) != 4 || offsetof(aItem::TCustomWeapon, CustomInfo) == 128);

} // namespace aItem
