#pragma once
#include "types/aPlayer.hpp"

namespace aPlayer {
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TPlanetBattleHistoryEntry) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlanetBattleHistoryEntry, MapId) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlanetBattleHistoryEntry, Statistics) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlanetBattleHistoryEntry, ResultCode) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlanetBattleHistoryEntry, CompletionMode) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlanetBattleHistoryEntry, DateTurn) == 36);
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TEquipmentConfiguration) == 176);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TEquipmentConfiguration, EquipmentIds) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TEquipmentConfiguration, ArtefactIds) == 48);
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TPlayer) == 3568);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, InPrison) == 1376);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, TalkLocked) == 1377);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ScanLocked) == 1378);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, HyperspaceKillCount) == 1380);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, BlackHoleKillCount) == 1384);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DominatorKillsByType) == 1388);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ScriptShipBindings) == 1420);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, QuestTargetKillShip) == 1424);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, QuestTargetDefendShip) == 1428);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, QuestTargetDefendStar) == 1432);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, StorageEntries) == 1436);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DebtAmount) == 1440);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DebtDueTurn) == 1444);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DebtDefaultCount) == 1448);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DepositAmount) == 1452);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DepositStartTurn) == 1456);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DepositDayCount) == 1460);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DepositInterestRate) == 1464);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, MedicalPolicyTicks) == 1468);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PirateLicenseTicks) == 1472);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PirateLicenseCash) == 1476);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PendingPirateLicenseCash) == 1480);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, QueuedTravelTarget) == 1484);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, StationServiceLastUseTurns) == 1488);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, StatusEffectSourceNames) == 1536);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DiseaseImmunity) == 1632);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ProgramRewardStocks) == 1636);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, LastDominatorProgramRewardTurn) == 1684);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DestroyedDominatorHullMass) == 1688);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, Satellites) == 1692);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PlanetBattleHistory) == 1696);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PlanetBattles) == 1700);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, LastPlanetBattleTurn) == 1704);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DeclinePlanetBattleOffers) == 1708);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, DiseaseContractionCount) == 1710);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, StimulantPurchaseCount) == 1712);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PrisonStaysCompleted) == 1714);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, SatelliteTilesExplored) == 1716);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, NationalityChangeCount) == 1720);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, SideChangeCount) == 1724);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, SelectedEquipmentConfiguration) == 1728);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, EquipmentConfigurations) == 1732);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PiratePartners) == 3492);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, UnresolvedFlagsDA8) == 3496);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, JournalRecords) == 3504);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, NewsEntries) == 3508);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PendingDockDialogue) == 3512);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, NoJump) == 3513);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, PirateClanReal) == 3514);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, AchievementStats) == 3516);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ExperienceByDominators) == 3520);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ExperienceByPirates) == 3524);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ExperienceByNormals) == 3528);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ExperienceByTraderCareer) == 3532);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, RuinsMode) == 3536);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, RuinsProxy) == 3540);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, RuinsSavedDockedTo) == 3544);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, RuinsSavedPlanet) == 3548);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, RuinsStatusText) == 3552);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, AwardedAchievementKeys) == 3556);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, BombKillsThisTurn) == 3560);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TPlayer, ChameleonLogic) == 3564);
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TStorageEntry) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageEntry, LocationOwner) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageEntry, SlotIndex) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageEntry, Item) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TStorageItemColumns) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageItemColumns, Heading) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageItemColumns, Size) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageItemColumns, Cost) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TStorageHeaderColumns) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageHeaderColumns, Size) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TStorageHeaderColumns, Cost) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TProbeSummaryColumns) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TProbeSummaryColumns, Heading) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TProbeSummaryColumns, Size) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TProbeSummaryColumns, Exploration) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TProbeSummaryColumns, Condition) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TProbeSummaryColumns, Status) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aPlayer::TJournalRecord) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TJournalRecord, DateTurn) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aPlayer::TJournalRecord, Text) == 8);

} // namespace aPlayer
