#pragma once
#include "types/aScript.hpp"

namespace aScript {
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptGroupRelation) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroupRelation, Group1) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroupRelation, Group2) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroupRelation, Relation1To2) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroupRelation, Relation2To1) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroupRelation, MinCombatBalance) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroupRelation, MaxCombatBalance) == 20);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScript) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, ClassId) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, ScriptFileName) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Constellations) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Stars) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Places) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Items) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Groups) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Ships) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, States) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Dialogs) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, DialogMessages) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, DialogAnswers) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, InitCode) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, TurnCode) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, DialogCode) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, Ether) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, CurrentShip) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, CurrentDialog) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, CurrentAnswer) == 76);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, SkipGreeting) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, GroupRelations) == 84);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, AnchorPlanet) == 88);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScript, EtherIds) == 92);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptTQRequest) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptTQRequest, Name) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptTQRequest, SuccessCaption) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptTQRequest, FailureCaption) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptTQRequest, Script) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptABRequest) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptABRequest, MapName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptABRequest, Ships) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptABRequest, BackgroundId) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptABRequest, BackgroundMapName) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptABRequest, Script) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptPBRequest) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPBRequest, MapName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPBRequest, StartText) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPBRequest, SuccessText) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPBRequest, FailureText) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPBRequest, PlaceText) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPBRequest, Script) == 20);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptVDRequest) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptVDRequest, Video) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptVDRequest, Soundtrack) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptVDRequest, Script) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptItem) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, LocationVarName) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, DefinitionKind) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, DefinitionType) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, Weight) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, Level) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, DefinitionValue1C) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, OwnerId) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, ConfigName) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, Item) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, CanSell) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, Data) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, TextData1) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, TextData2) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, TextData3) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, OnUseText) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, OnActionText) == 76);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, ActionCode) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, ActionTypeMask) == 84);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, StepTypeMask) == 92);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, ActionCodeInitialized) == 94);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptItem, Script) == 96);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptContextSnapshot) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptContextSnapshot, Script) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptContextSnapshot, CurrentShip) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptContextSnapshot, EndState) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptCache) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptCache, Entries) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TLibraryCache) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TLibraryCache, Libraries) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptGICache) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGICache, Entries) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TLibraryHandler) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TLibraryHandler, LibraryName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TLibraryHandler, ModuleHandle) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TLibraryHandler, DefinitionBlock) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptShip) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, Script) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, GroupIndex) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, Ship) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, Data) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, State) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, StateText) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, EndState) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, Hit) == 41);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShip, HitPlayer) == 42);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptState) == 76);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, StateKind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, TargetVarName) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, TargetValue) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, EnemyGroupNames) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, EnemyGroupIndices) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, PickupItemVarName) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, PickupItem) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, PickUpNearbyItems) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, DialogTextOrVariable) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, DialogCode) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, OnActionText) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, ActionCode) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, ActionTypeMask) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, StepTypeMask) == 64);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, EntryCode) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptState, StateCode) == 72);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptThread) == 44);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptCacheUnit) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptCacheUnit, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptCacheUnit, SourceText) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptCacheUnit, Code) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptCacheUnit, ActionTypeMask) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptCacheUnit, StepTypeMask) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptPlace) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, Script) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, Name) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, OriginVarName) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, OriginStar) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, PlaceKind) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, AngleOffset) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, DistanceScale) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, Radius) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, TargetVarName) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, TargetValue) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, TargetVarName2) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlace, TargetValue2) == 48);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptStarConstraint) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStarConstraint, OtherStar) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStarConstraint, MinDistance) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStarConstraint, MaxDistance) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStarConstraint, RequireBlackHole) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptPlanet) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, Name) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, RaceMask) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, OwnerMask) == 5);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, EconomyMask) == 6);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, GovernmentMask) == 7);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, MinOrbitPercent) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, MaxOrbitPercent) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, DialogChoiceText) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptPlanet, Planet) == 20);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptShipOtb) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, Count) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, OwnerMask) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, ShipTypeMask) == 5);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, PlayerOnly) == 7);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MinSpeed) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MaxSpeed) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, WeaponRequirement) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MinCargoHookLevel) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MinFreeCargoSpace) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MinTraderStatus) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MaxTraderStatus) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MinWarriorStatus) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MaxWarriorStatus) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MinPirateStatus) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MaxPirateStatus) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MinStrength) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, MaxStrength) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, StationNames) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptShipOtb, DominatorMasks) == 64);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptStar) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, ConstellationIndex) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, RejectHostilePresence) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, ProtectStar) == 13);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, Constraints) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, Planets) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, ShipRequirements) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptStar, Star) == 28);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptConstellation) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptConstellation, Constellation) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptGroup) == 112);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, PlanetVarName) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, Planet) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, InitialStateIndex) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, OwnerMask) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, ShipTypeMask) == 21);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinCount) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MaxCount) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinSpeed) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MaxSpeed) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, WeaponRequirement) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinCargoHookLevel) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinFreeCargoSpace) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, IncludePlayer) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, StationNames) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, DominatorMasks) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinStrength) == 68);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MaxStrength) == 72);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinTraderStatus) == 76);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MaxTraderStatus) == 80);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinWarriorStatus) == 84);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MaxWarriorStatus) == 88);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MinPirateStatus) == 92);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MaxPirateStatus) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, MaxDistanceFromPlanet) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, StationDialogVariable) == 104);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGroup, Ships) == 108);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptDialog) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptDialog, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptDialog, Code) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptDialogMsg) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptDialogMsg, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptDialogMsg, Code) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptDialogAnswer) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptDialogAnswer, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptDialogAnswer, AnswerCode) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptDialogAnswer, ActionCode) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TDialogBlock) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogBlock, Text) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogBlock, Script) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogBlock, Mode) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TDialogInject) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, Script) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, DialogName) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, Text) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, Answer) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, Priority) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, AnswerData) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, ReplaceGreeting) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, ActionCode) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogInject, ActionScript) == 32);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TDialogOverride) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogOverride, DialogName) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogOverride, Priority) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogOverride, Script) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TDialogOverride, AnswerData) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(aScript::TScriptGICacheUnit) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGICacheUnit, Block) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGICacheUnit, SourceText) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(aScript::TScriptGICacheUnit, Code) == 12);

} // namespace aScript
