#pragma once
#include "types/EC_Expression.hpp"

namespace EC_Expression {
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TVarArrayEC) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarArrayEC, Count) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarArrayEC, Data) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarArrayEC, NameOrder) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TVarEC) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, Name) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, Kind) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, IntValue) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, DwordValue) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, StringValue) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, FloatValue) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, ExternFunValue) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, LibraryFunData) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, FunctionValue) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, ClassValue) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, ArrayValue) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TVarEC, RefValue) == 52);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCodeEC) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, Parent) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, IsClassDefinition) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, Name) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, First) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, Last) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, LocalVar) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, Process) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, DebugContext) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeEC, ScriptFunLinked) == 36);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCodeUnitEC) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, Prev) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, Next) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, Opcode) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, Expression) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, Target) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, ExceptionVar) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, SourceStart) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, SourceLength) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, SourceContext) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeUnitEC, Breakpoint) == 40);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TExpressionEC) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionEC, VariableCount) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionEC, Variables) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionEC, InstructionCount) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionEC, Instructions) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionEC, SharedInstructions) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionEC, ResultIndex) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TExpressionVarEC) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionVarEC, Kind) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionVarEC, Name) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionVarEC, MemberPath) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionVarEC, Value) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TExpressionInstrEC) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionInstrEC, Opcode) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionInstrEC, OperandCount) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TExpressionInstrEC, Operands) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCodeProcessEC) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeProcessEC, Handlers) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeProcessEC, Exceptions) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TScriptDebugState) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TScriptDebugState, Paused) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TScriptDebugState, StopEvent) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TScriptDebugState, ResumeEvent) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TScriptDebugState, StepMode) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TScriptDebugState, CurrentUnit) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TScriptDebugState, CurrentCode) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::ExceptionExpressionEC) == 12);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCodeExceptionHandler) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeExceptionHandler, Code) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeExceptionHandler, Handler) == 4);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCodeAnalyzerEC) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerEC, FirstFree) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerEC, LastFree) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerEC, First) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerEC, Last) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCodeAnalyzerUnitEC) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerUnitEC, Prev) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerUnitEC, Next) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerUnitEC, TokenKind) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerUnitEC, SourceStart) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerUnitEC, SourceLength) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCodeAnalyzerUnitEC, Text) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCompilerEC) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerEC, First) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerEC, Last) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(EC_Expression::TCompilerUnitEC) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, Prev) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, Next) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, Kind) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, OperatorToken) == 13);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, Text) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, VariableIndex) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, IntValue) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, DwordValue) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, FloatValue) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, SourceStart) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(EC_Expression::TCompilerUnitEC, SourceLength) == 44);

} // namespace EC_Expression
