#pragma once
#include "types/Windows_group.hpp"

namespace WindowsSdk {
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::pas_SECURITY_ATTRIBUTES) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_SECURITY_ATTRIBUTES, nLength) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_SECURITY_ATTRIBUTES, lpSecurityDescriptor) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_SECURITY_ATTRIBUTES, bInheritHandle) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::pas_ICONINFO) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_ICONINFO, fIcon) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_ICONINFO, xHotspot) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_ICONINFO, yHotspot) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_ICONINFO, hbmMask) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_ICONINFO, hbmColor) == 16);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::tagCIEXYZ) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagCIEXYZ, ciexyzX) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagCIEXYZ, ciexyzY) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagCIEXYZ, ciexyzZ) == 8);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::tagICEXYZTRIPLE) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagICEXYZTRIPLE, ciexyzRed) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagICEXYZTRIPLE, ciexyzGreen) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagICEXYZTRIPLE, ciexyzBlue) == 24);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::BITMAPV4HEADER) == 108);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4Size) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4Width) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4Height) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4Planes) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4BitCount) == 14);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4V4Compression) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4SizeImage) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4XPelsPerMeter) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4YPelsPerMeter) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4ClrUsed) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4ClrImportant) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4RedMask) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4GreenMask) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4BlueMask) == 48);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4AlphaMask) == 52);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4CSType) == 56);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4Endpoints) == 60);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4GammaRed) == 96);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4GammaGreen) == 100);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::BITMAPV4HEADER, bV4GammaBlue) == 104);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::tagBITMAPINFOHEADER) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biSize) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biWidth) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biHeight) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biPlanes) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biBitCount) == 14);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biCompression) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biSizeImage) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biXPelsPerMeter) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biYPelsPerMeter) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biClrUsed) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFOHEADER, biClrImportant) == 36);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::tagRGBQUAD) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagRGBQUAD, rgbBlue) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagRGBQUAD, rgbGreen) == 1);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagRGBQUAD, rgbRed) == 2);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagRGBQUAD, rgbReserved) == 3);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::tagBITMAPINFO) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFO, bmiHeader) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagBITMAPINFO, bmiColors) == 40);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::pas_SYSTEM_INFO) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_SYSTEM_INFO, dwOemId) == 0);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::tagWNDCLASSW) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, style) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, lpfnWndProc) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, cbClsExtra) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, cbWndExtra) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, hInstance) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, hIcon) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, hCursor) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, hbrBackground) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, lpszMenuName) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::tagWNDCLASSW, lpszClassName) == 36);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::pas_MEMORYSTATUS) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwLength) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwMemoryLoad) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwTotalPhys) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwAvailPhys) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwTotalPageFile) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwAvailPageFile) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwTotalVirtual) == 24);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_MEMORYSTATUS, dwAvailVirtual) == 28);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::pas_OSVERSIONINFOA) == 148);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_OSVERSIONINFOA, dwOSVersionInfoSize) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_OSVERSIONINFOA, dwMajorVersion) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_OSVERSIONINFOA, dwMinorVersion) == 8);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_OSVERSIONINFOA, dwBuildNumber) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_OSVERSIONINFOA, dwPlatformId) == 16);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_OSVERSIONINFOA, szCSDVersion) == 20);
    static_assert(sizeof(void*) != 4 || sizeof(WindowsSdk::pas_WIN32_FIND_DATAW) == 592);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, dwFileAttributes) == 0);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, ftCreationTime) == 4);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, ftLastAccessTime) == 12);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, ftLastWriteTime) == 20);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, nFileSizeHigh) == 28);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, nFileSizeLow) == 32);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, dwReserved0) == 36);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, dwReserved1) == 40);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, cFileName) == 44);
    static_assert(sizeof(void*) != 4 || offsetof(WindowsSdk::pas_WIN32_FIND_DATAW, cAlternateFileName) == 564);

} // namespace WindowsSdk
